// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // NOTE:
    // - `DATABASE_URL` may be a Prisma Accelerate URL (e.g. `prisma+postgres://...`) which is not suitable for migrations.
    // - For migrations/seeding, set `DIRECT_URL` to a real `postgresql://...` connection string.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
